// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mujoco_service.proto
#ifndef GRPC_mujoco_5fservice_2eproto__INCLUDED
#define GRPC_mujoco_5fservice_2eproto__INCLUDED

#include "mujoco_service.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace mujoco {

// Service for MuJoCo simulation control
class MuJoCoService final {
 public:
  static constexpr char const* service_full_name() {
    return "mujoco.MuJoCoService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Fetch observation from MuJoCo
    virtual ::grpc::Status FetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::mujoco::FetchObsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mujoco::FetchObsResponse>> AsyncFetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mujoco::FetchObsResponse>>(AsyncFetchObsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mujoco::FetchObsResponse>> PrepareAsyncFetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mujoco::FetchObsResponse>>(PrepareAsyncFetchObsRaw(context, request, cq));
    }
    // Write torque commands to MuJoCo
    virtual ::grpc::Status WriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::mujoco::WriteTorqueResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mujoco::WriteTorqueResponse>> AsyncWriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mujoco::WriteTorqueResponse>>(AsyncWriteTorqueRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mujoco::WriteTorqueResponse>> PrepareAsyncWriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mujoco::WriteTorqueResponse>>(PrepareAsyncWriteTorqueRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Fetch observation from MuJoCo
      virtual void FetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest* request, ::mujoco::FetchObsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FetchObs(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::FetchObsResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void FetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest* request, ::mujoco::FetchObsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void FetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest* request, ::mujoco::FetchObsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void FetchObs(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::FetchObsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void FetchObs(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::FetchObsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Write torque commands to MuJoCo
      virtual void WriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest* request, ::mujoco::WriteTorqueResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void WriteTorque(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::WriteTorqueResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void WriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest* request, ::mujoco::WriteTorqueResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void WriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest* request, ::mujoco::WriteTorqueResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void WriteTorque(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::WriteTorqueResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void WriteTorque(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::WriteTorqueResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mujoco::FetchObsResponse>* AsyncFetchObsRaw(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mujoco::FetchObsResponse>* PrepareAsyncFetchObsRaw(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mujoco::WriteTorqueResponse>* AsyncWriteTorqueRaw(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mujoco::WriteTorqueResponse>* PrepareAsyncWriteTorqueRaw(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status FetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::mujoco::FetchObsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mujoco::FetchObsResponse>> AsyncFetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mujoco::FetchObsResponse>>(AsyncFetchObsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mujoco::FetchObsResponse>> PrepareAsyncFetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mujoco::FetchObsResponse>>(PrepareAsyncFetchObsRaw(context, request, cq));
    }
    ::grpc::Status WriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::mujoco::WriteTorqueResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mujoco::WriteTorqueResponse>> AsyncWriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mujoco::WriteTorqueResponse>>(AsyncWriteTorqueRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mujoco::WriteTorqueResponse>> PrepareAsyncWriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mujoco::WriteTorqueResponse>>(PrepareAsyncWriteTorqueRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void FetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest* request, ::mujoco::FetchObsResponse* response, std::function<void(::grpc::Status)>) override;
      void FetchObs(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::FetchObsResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void FetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest* request, ::mujoco::FetchObsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void FetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest* request, ::mujoco::FetchObsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void FetchObs(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::FetchObsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void FetchObs(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::FetchObsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void WriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest* request, ::mujoco::WriteTorqueResponse* response, std::function<void(::grpc::Status)>) override;
      void WriteTorque(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::WriteTorqueResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void WriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest* request, ::mujoco::WriteTorqueResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void WriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest* request, ::mujoco::WriteTorqueResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void WriteTorque(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::WriteTorqueResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void WriteTorque(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::WriteTorqueResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mujoco::FetchObsResponse>* AsyncFetchObsRaw(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mujoco::FetchObsResponse>* PrepareAsyncFetchObsRaw(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mujoco::WriteTorqueResponse>* AsyncWriteTorqueRaw(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mujoco::WriteTorqueResponse>* PrepareAsyncWriteTorqueRaw(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FetchObs_;
    const ::grpc::internal::RpcMethod rpcmethod_WriteTorque_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Fetch observation from MuJoCo
    virtual ::grpc::Status FetchObs(::grpc::ServerContext* context, const ::mujoco::FetchObsRequest* request, ::mujoco::FetchObsResponse* response);
    // Write torque commands to MuJoCo
    virtual ::grpc::Status WriteTorque(::grpc::ServerContext* context, const ::mujoco::WriteTorqueRequest* request, ::mujoco::WriteTorqueResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_FetchObs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FetchObs() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FetchObs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchObs(::grpc::ServerContext* /*context*/, const ::mujoco::FetchObsRequest* /*request*/, ::mujoco::FetchObsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchObs(::grpc::ServerContext* context, ::mujoco::FetchObsRequest* request, ::grpc::ServerAsyncResponseWriter< ::mujoco::FetchObsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_WriteTorque : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_WriteTorque() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_WriteTorque() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteTorque(::grpc::ServerContext* /*context*/, const ::mujoco::WriteTorqueRequest* /*request*/, ::mujoco::WriteTorqueResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWriteTorque(::grpc::ServerContext* context, ::mujoco::WriteTorqueRequest* request, ::grpc::ServerAsyncResponseWriter< ::mujoco::WriteTorqueResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FetchObs<WithAsyncMethod_WriteTorque<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_FetchObs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_FetchObs() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::mujoco::FetchObsRequest, ::mujoco::FetchObsResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::mujoco::FetchObsRequest* request, ::mujoco::FetchObsResponse* response) { return this->FetchObs(context, request, response); }));}
    void SetMessageAllocatorFor_FetchObs(
        ::grpc::experimental::MessageAllocator< ::mujoco::FetchObsRequest, ::mujoco::FetchObsResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::mujoco::FetchObsRequest, ::mujoco::FetchObsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_FetchObs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchObs(::grpc::ServerContext* /*context*/, const ::mujoco::FetchObsRequest* /*request*/, ::mujoco::FetchObsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* FetchObs(
      ::grpc::CallbackServerContext* /*context*/, const ::mujoco::FetchObsRequest* /*request*/, ::mujoco::FetchObsResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* FetchObs(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::mujoco::FetchObsRequest* /*request*/, ::mujoco::FetchObsResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_WriteTorque : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_WriteTorque() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::mujoco::WriteTorqueRequest, ::mujoco::WriteTorqueResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::mujoco::WriteTorqueRequest* request, ::mujoco::WriteTorqueResponse* response) { return this->WriteTorque(context, request, response); }));}
    void SetMessageAllocatorFor_WriteTorque(
        ::grpc::experimental::MessageAllocator< ::mujoco::WriteTorqueRequest, ::mujoco::WriteTorqueResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::mujoco::WriteTorqueRequest, ::mujoco::WriteTorqueResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_WriteTorque() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteTorque(::grpc::ServerContext* /*context*/, const ::mujoco::WriteTorqueRequest* /*request*/, ::mujoco::WriteTorqueResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* WriteTorque(
      ::grpc::CallbackServerContext* /*context*/, const ::mujoco::WriteTorqueRequest* /*request*/, ::mujoco::WriteTorqueResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* WriteTorque(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::mujoco::WriteTorqueRequest* /*request*/, ::mujoco::WriteTorqueResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_FetchObs<ExperimentalWithCallbackMethod_WriteTorque<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_FetchObs<ExperimentalWithCallbackMethod_WriteTorque<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_FetchObs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FetchObs() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FetchObs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchObs(::grpc::ServerContext* /*context*/, const ::mujoco::FetchObsRequest* /*request*/, ::mujoco::FetchObsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_WriteTorque : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_WriteTorque() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_WriteTorque() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteTorque(::grpc::ServerContext* /*context*/, const ::mujoco::WriteTorqueRequest* /*request*/, ::mujoco::WriteTorqueResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_FetchObs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FetchObs() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_FetchObs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchObs(::grpc::ServerContext* /*context*/, const ::mujoco::FetchObsRequest* /*request*/, ::mujoco::FetchObsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchObs(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_WriteTorque : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_WriteTorque() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_WriteTorque() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteTorque(::grpc::ServerContext* /*context*/, const ::mujoco::WriteTorqueRequest* /*request*/, ::mujoco::WriteTorqueResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWriteTorque(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_FetchObs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_FetchObs() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FetchObs(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_FetchObs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchObs(::grpc::ServerContext* /*context*/, const ::mujoco::FetchObsRequest* /*request*/, ::mujoco::FetchObsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* FetchObs(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* FetchObs(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_WriteTorque : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_WriteTorque() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->WriteTorque(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_WriteTorque() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteTorque(::grpc::ServerContext* /*context*/, const ::mujoco::WriteTorqueRequest* /*request*/, ::mujoco::WriteTorqueResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* WriteTorque(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* WriteTorque(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FetchObs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FetchObs() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mujoco::FetchObsRequest, ::mujoco::FetchObsResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::mujoco::FetchObsRequest, ::mujoco::FetchObsResponse>* streamer) {
                       return this->StreamedFetchObs(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FetchObs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FetchObs(::grpc::ServerContext* /*context*/, const ::mujoco::FetchObsRequest* /*request*/, ::mujoco::FetchObsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFetchObs(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mujoco::FetchObsRequest,::mujoco::FetchObsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_WriteTorque : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_WriteTorque() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mujoco::WriteTorqueRequest, ::mujoco::WriteTorqueResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::mujoco::WriteTorqueRequest, ::mujoco::WriteTorqueResponse>* streamer) {
                       return this->StreamedWriteTorque(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_WriteTorque() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status WriteTorque(::grpc::ServerContext* /*context*/, const ::mujoco::WriteTorqueRequest* /*request*/, ::mujoco::WriteTorqueResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedWriteTorque(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mujoco::WriteTorqueRequest,::mujoco::WriteTorqueResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_FetchObs<WithStreamedUnaryMethod_WriteTorque<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_FetchObs<WithStreamedUnaryMethod_WriteTorque<Service > > StreamedService;
};

}  // namespace mujoco


#endif  // GRPC_mujoco_5fservice_2eproto__INCLUDED
