// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mujoco_service.proto

#include "mujoco_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace mujoco {
class FetchObsRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FetchObsRequest> _instance;
} _FetchObsRequest_default_instance_;
class FetchObsResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FetchObsResponse> _instance;
} _FetchObsResponse_default_instance_;
class WriteTorqueRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<WriteTorqueRequest> _instance;
} _WriteTorqueRequest_default_instance_;
class WriteTorqueResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<WriteTorqueResponse> _instance;
} _WriteTorqueResponse_default_instance_;
}  // namespace mujoco
static void InitDefaultsscc_info_FetchObsRequest_mujoco_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mujoco::_FetchObsRequest_default_instance_;
    new (ptr) ::mujoco::FetchObsRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mujoco::FetchObsRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_FetchObsRequest_mujoco_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_FetchObsRequest_mujoco_5fservice_2eproto}, {}};

static void InitDefaultsscc_info_FetchObsResponse_mujoco_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mujoco::_FetchObsResponse_default_instance_;
    new (ptr) ::mujoco::FetchObsResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mujoco::FetchObsResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_FetchObsResponse_mujoco_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_FetchObsResponse_mujoco_5fservice_2eproto}, {}};

static void InitDefaultsscc_info_WriteTorqueRequest_mujoco_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mujoco::_WriteTorqueRequest_default_instance_;
    new (ptr) ::mujoco::WriteTorqueRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mujoco::WriteTorqueRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_WriteTorqueRequest_mujoco_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_WriteTorqueRequest_mujoco_5fservice_2eproto}, {}};

static void InitDefaultsscc_info_WriteTorqueResponse_mujoco_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mujoco::_WriteTorqueResponse_default_instance_;
    new (ptr) ::mujoco::WriteTorqueResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mujoco::WriteTorqueResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_WriteTorqueResponse_mujoco_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_WriteTorqueResponse_mujoco_5fservice_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_mujoco_5fservice_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_mujoco_5fservice_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_mujoco_5fservice_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_mujoco_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mujoco::FetchObsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mujoco::FetchObsResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mujoco::FetchObsResponse, base_ang_vel_),
  PROTOBUF_FIELD_OFFSET(::mujoco::FetchObsResponse, joint_pos_),
  PROTOBUF_FIELD_OFFSET(::mujoco::FetchObsResponse, joint_vel_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mujoco::WriteTorqueRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mujoco::WriteTorqueRequest, torques_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mujoco::WriteTorqueResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mujoco::WriteTorqueResponse, success_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::mujoco::FetchObsRequest)},
  { 5, -1, sizeof(::mujoco::FetchObsResponse)},
  { 13, -1, sizeof(::mujoco::WriteTorqueRequest)},
  { 19, -1, sizeof(::mujoco::WriteTorqueResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mujoco::_FetchObsRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mujoco::_FetchObsResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mujoco::_WriteTorqueRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mujoco::_WriteTorqueResponse_default_instance_),
};

const char descriptor_table_protodef_mujoco_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024mujoco_service.proto\022\006mujoco\"\021\n\017FetchO"
  "bsRequest\"N\n\020FetchObsResponse\022\024\n\014base_an"
  "g_vel\030\001 \003(\002\022\021\n\tjoint_pos\030\002 \003(\002\022\021\n\tjoint_"
  "vel\030\003 \003(\002\"%\n\022WriteTorqueRequest\022\017\n\007torqu"
  "es\030\001 \003(\002\"&\n\023WriteTorqueResponse\022\017\n\007succe"
  "ss\030\001 \001(\0102\226\001\n\rMuJoCoService\022=\n\010FetchObs\022\027"
  ".mujoco.FetchObsRequest\032\030.mujoco.FetchOb"
  "sResponse\022F\n\013WriteTorque\022\032.mujoco.WriteT"
  "orqueRequest\032\033.mujoco.WriteTorqueRespons"
  "eb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_mujoco_5fservice_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_mujoco_5fservice_2eproto_sccs[4] = {
  &scc_info_FetchObsRequest_mujoco_5fservice_2eproto.base,
  &scc_info_FetchObsResponse_mujoco_5fservice_2eproto.base,
  &scc_info_WriteTorqueRequest_mujoco_5fservice_2eproto.base,
  &scc_info_WriteTorqueResponse_mujoco_5fservice_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_mujoco_5fservice_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mujoco_5fservice_2eproto = {
  false, false, descriptor_table_protodef_mujoco_5fservice_2eproto, "mujoco_service.proto", 369,
  &descriptor_table_mujoco_5fservice_2eproto_once, descriptor_table_mujoco_5fservice_2eproto_sccs, descriptor_table_mujoco_5fservice_2eproto_deps, 4, 0,
  schemas, file_default_instances, TableStruct_mujoco_5fservice_2eproto::offsets,
  file_level_metadata_mujoco_5fservice_2eproto, 4, file_level_enum_descriptors_mujoco_5fservice_2eproto, file_level_service_descriptors_mujoco_5fservice_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_mujoco_5fservice_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_mujoco_5fservice_2eproto)), true);
namespace mujoco {

// ===================================================================

void FetchObsRequest::InitAsDefaultInstance() {
}
class FetchObsRequest::_Internal {
 public:
};

FetchObsRequest::FetchObsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:mujoco.FetchObsRequest)
}
FetchObsRequest::FetchObsRequest(const FetchObsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mujoco.FetchObsRequest)
}

void FetchObsRequest::SharedCtor() {
}

FetchObsRequest::~FetchObsRequest() {
  // @@protoc_insertion_point(destructor:mujoco.FetchObsRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void FetchObsRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void FetchObsRequest::ArenaDtor(void* object) {
  FetchObsRequest* _this = reinterpret_cast< FetchObsRequest* >(object);
  (void)_this;
}
void FetchObsRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FetchObsRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FetchObsRequest& FetchObsRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FetchObsRequest_mujoco_5fservice_2eproto.base);
  return *internal_default_instance();
}


void FetchObsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mujoco.FetchObsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FetchObsRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FetchObsRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mujoco.FetchObsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mujoco.FetchObsRequest)
  return target;
}

size_t FetchObsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mujoco.FetchObsRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FetchObsRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mujoco.FetchObsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const FetchObsRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FetchObsRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mujoco.FetchObsRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mujoco.FetchObsRequest)
    MergeFrom(*source);
  }
}

void FetchObsRequest::MergeFrom(const FetchObsRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mujoco.FetchObsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void FetchObsRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mujoco.FetchObsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FetchObsRequest::CopyFrom(const FetchObsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mujoco.FetchObsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FetchObsRequest::IsInitialized() const {
  return true;
}

void FetchObsRequest::InternalSwap(FetchObsRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FetchObsRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void FetchObsResponse::InitAsDefaultInstance() {
}
class FetchObsResponse::_Internal {
 public:
};

FetchObsResponse::FetchObsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  base_ang_vel_(arena),
  joint_pos_(arena),
  joint_vel_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:mujoco.FetchObsResponse)
}
FetchObsResponse::FetchObsResponse(const FetchObsResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      base_ang_vel_(from.base_ang_vel_),
      joint_pos_(from.joint_pos_),
      joint_vel_(from.joint_vel_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mujoco.FetchObsResponse)
}

void FetchObsResponse::SharedCtor() {
}

FetchObsResponse::~FetchObsResponse() {
  // @@protoc_insertion_point(destructor:mujoco.FetchObsResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void FetchObsResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void FetchObsResponse::ArenaDtor(void* object) {
  FetchObsResponse* _this = reinterpret_cast< FetchObsResponse* >(object);
  (void)_this;
}
void FetchObsResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FetchObsResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FetchObsResponse& FetchObsResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FetchObsResponse_mujoco_5fservice_2eproto.base);
  return *internal_default_instance();
}


void FetchObsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:mujoco.FetchObsResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  base_ang_vel_.Clear();
  joint_pos_.Clear();
  joint_vel_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FetchObsResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated float base_ang_vel = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_base_ang_vel(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13) {
          _internal_add_base_ang_vel(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float joint_pos = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_joint_pos(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21) {
          _internal_add_joint_pos(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float joint_vel = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_joint_vel(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29) {
          _internal_add_joint_vel(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FetchObsResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mujoco.FetchObsResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float base_ang_vel = 1;
  if (this->_internal_base_ang_vel_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_base_ang_vel(), target);
  }

  // repeated float joint_pos = 2;
  if (this->_internal_joint_pos_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_joint_pos(), target);
  }

  // repeated float joint_vel = 3;
  if (this->_internal_joint_vel_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_joint_vel(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mujoco.FetchObsResponse)
  return target;
}

size_t FetchObsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mujoco.FetchObsResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float base_ang_vel = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_base_ang_vel_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _base_ang_vel_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float joint_pos = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_joint_pos_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _joint_pos_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float joint_vel = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_joint_vel_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _joint_vel_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FetchObsResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mujoco.FetchObsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const FetchObsResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FetchObsResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mujoco.FetchObsResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mujoco.FetchObsResponse)
    MergeFrom(*source);
  }
}

void FetchObsResponse::MergeFrom(const FetchObsResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mujoco.FetchObsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  base_ang_vel_.MergeFrom(from.base_ang_vel_);
  joint_pos_.MergeFrom(from.joint_pos_);
  joint_vel_.MergeFrom(from.joint_vel_);
}

void FetchObsResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mujoco.FetchObsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FetchObsResponse::CopyFrom(const FetchObsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mujoco.FetchObsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FetchObsResponse::IsInitialized() const {
  return true;
}

void FetchObsResponse::InternalSwap(FetchObsResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  base_ang_vel_.InternalSwap(&other->base_ang_vel_);
  joint_pos_.InternalSwap(&other->joint_pos_);
  joint_vel_.InternalSwap(&other->joint_vel_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FetchObsResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void WriteTorqueRequest::InitAsDefaultInstance() {
}
class WriteTorqueRequest::_Internal {
 public:
};

WriteTorqueRequest::WriteTorqueRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  torques_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:mujoco.WriteTorqueRequest)
}
WriteTorqueRequest::WriteTorqueRequest(const WriteTorqueRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      torques_(from.torques_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mujoco.WriteTorqueRequest)
}

void WriteTorqueRequest::SharedCtor() {
}

WriteTorqueRequest::~WriteTorqueRequest() {
  // @@protoc_insertion_point(destructor:mujoco.WriteTorqueRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void WriteTorqueRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void WriteTorqueRequest::ArenaDtor(void* object) {
  WriteTorqueRequest* _this = reinterpret_cast< WriteTorqueRequest* >(object);
  (void)_this;
}
void WriteTorqueRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void WriteTorqueRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WriteTorqueRequest& WriteTorqueRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_WriteTorqueRequest_mujoco_5fservice_2eproto.base);
  return *internal_default_instance();
}


void WriteTorqueRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mujoco.WriteTorqueRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  torques_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WriteTorqueRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated float torques = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_torques(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13) {
          _internal_add_torques(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* WriteTorqueRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mujoco.WriteTorqueRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float torques = 1;
  if (this->_internal_torques_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_torques(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mujoco.WriteTorqueRequest)
  return target;
}

size_t WriteTorqueRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mujoco.WriteTorqueRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float torques = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_torques_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _torques_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WriteTorqueRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mujoco.WriteTorqueRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const WriteTorqueRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<WriteTorqueRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mujoco.WriteTorqueRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mujoco.WriteTorqueRequest)
    MergeFrom(*source);
  }
}

void WriteTorqueRequest::MergeFrom(const WriteTorqueRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mujoco.WriteTorqueRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  torques_.MergeFrom(from.torques_);
}

void WriteTorqueRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mujoco.WriteTorqueRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WriteTorqueRequest::CopyFrom(const WriteTorqueRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mujoco.WriteTorqueRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WriteTorqueRequest::IsInitialized() const {
  return true;
}

void WriteTorqueRequest::InternalSwap(WriteTorqueRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  torques_.InternalSwap(&other->torques_);
}

::PROTOBUF_NAMESPACE_ID::Metadata WriteTorqueRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void WriteTorqueResponse::InitAsDefaultInstance() {
}
class WriteTorqueResponse::_Internal {
 public:
};

WriteTorqueResponse::WriteTorqueResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:mujoco.WriteTorqueResponse)
}
WriteTorqueResponse::WriteTorqueResponse(const WriteTorqueResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  success_ = from.success_;
  // @@protoc_insertion_point(copy_constructor:mujoco.WriteTorqueResponse)
}

void WriteTorqueResponse::SharedCtor() {
  success_ = false;
}

WriteTorqueResponse::~WriteTorqueResponse() {
  // @@protoc_insertion_point(destructor:mujoco.WriteTorqueResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void WriteTorqueResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void WriteTorqueResponse::ArenaDtor(void* object) {
  WriteTorqueResponse* _this = reinterpret_cast< WriteTorqueResponse* >(object);
  (void)_this;
}
void WriteTorqueResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void WriteTorqueResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WriteTorqueResponse& WriteTorqueResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_WriteTorqueResponse_mujoco_5fservice_2eproto.base);
  return *internal_default_instance();
}


void WriteTorqueResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:mujoco.WriteTorqueResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WriteTorqueResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* WriteTorqueResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mujoco.WriteTorqueResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mujoco.WriteTorqueResponse)
  return target;
}

size_t WriteTorqueResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mujoco.WriteTorqueResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->success() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WriteTorqueResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mujoco.WriteTorqueResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const WriteTorqueResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<WriteTorqueResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mujoco.WriteTorqueResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mujoco.WriteTorqueResponse)
    MergeFrom(*source);
  }
}

void WriteTorqueResponse::MergeFrom(const WriteTorqueResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mujoco.WriteTorqueResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.success() != 0) {
    _internal_set_success(from._internal_success());
  }
}

void WriteTorqueResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mujoco.WriteTorqueResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WriteTorqueResponse::CopyFrom(const WriteTorqueResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mujoco.WriteTorqueResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WriteTorqueResponse::IsInitialized() const {
  return true;
}

void WriteTorqueResponse::InternalSwap(WriteTorqueResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(success_, other->success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata WriteTorqueResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace mujoco
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mujoco::FetchObsRequest* Arena::CreateMaybeMessage< ::mujoco::FetchObsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mujoco::FetchObsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mujoco::FetchObsResponse* Arena::CreateMaybeMessage< ::mujoco::FetchObsResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mujoco::FetchObsResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::mujoco::WriteTorqueRequest* Arena::CreateMaybeMessage< ::mujoco::WriteTorqueRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mujoco::WriteTorqueRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mujoco::WriteTorqueResponse* Arena::CreateMaybeMessage< ::mujoco::WriteTorqueResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mujoco::WriteTorqueResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
