// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mujoco_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mujoco_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mujoco_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mujoco_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mujoco_5fservice_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mujoco_5fservice_2eproto;
namespace mujoco {
class FetchObsRequest;
class FetchObsRequestDefaultTypeInternal;
extern FetchObsRequestDefaultTypeInternal _FetchObsRequest_default_instance_;
class FetchObsResponse;
class FetchObsResponseDefaultTypeInternal;
extern FetchObsResponseDefaultTypeInternal _FetchObsResponse_default_instance_;
class WriteTorqueRequest;
class WriteTorqueRequestDefaultTypeInternal;
extern WriteTorqueRequestDefaultTypeInternal _WriteTorqueRequest_default_instance_;
class WriteTorqueResponse;
class WriteTorqueResponseDefaultTypeInternal;
extern WriteTorqueResponseDefaultTypeInternal _WriteTorqueResponse_default_instance_;
}  // namespace mujoco
PROTOBUF_NAMESPACE_OPEN
template<> ::mujoco::FetchObsRequest* Arena::CreateMaybeMessage<::mujoco::FetchObsRequest>(Arena*);
template<> ::mujoco::FetchObsResponse* Arena::CreateMaybeMessage<::mujoco::FetchObsResponse>(Arena*);
template<> ::mujoco::WriteTorqueRequest* Arena::CreateMaybeMessage<::mujoco::WriteTorqueRequest>(Arena*);
template<> ::mujoco::WriteTorqueResponse* Arena::CreateMaybeMessage<::mujoco::WriteTorqueResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mujoco {

// ===================================================================

class FetchObsRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mujoco.FetchObsRequest) */ {
 public:
  inline FetchObsRequest() : FetchObsRequest(nullptr) {};
  virtual ~FetchObsRequest();

  FetchObsRequest(const FetchObsRequest& from);
  FetchObsRequest(FetchObsRequest&& from) noexcept
    : FetchObsRequest() {
    *this = ::std::move(from);
  }

  inline FetchObsRequest& operator=(const FetchObsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FetchObsRequest& operator=(FetchObsRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FetchObsRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FetchObsRequest* internal_default_instance() {
    return reinterpret_cast<const FetchObsRequest*>(
               &_FetchObsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FetchObsRequest& a, FetchObsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FetchObsRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FetchObsRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FetchObsRequest* New() const final {
    return CreateMaybeMessage<FetchObsRequest>(nullptr);
  }

  FetchObsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FetchObsRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FetchObsRequest& from);
  void MergeFrom(const FetchObsRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FetchObsRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mujoco.FetchObsRequest";
  }
  protected:
  explicit FetchObsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mujoco_5fservice_2eproto);
    return ::descriptor_table_mujoco_5fservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:mujoco.FetchObsRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mujoco_5fservice_2eproto;
};
// -------------------------------------------------------------------

class FetchObsResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mujoco.FetchObsResponse) */ {
 public:
  inline FetchObsResponse() : FetchObsResponse(nullptr) {};
  virtual ~FetchObsResponse();

  FetchObsResponse(const FetchObsResponse& from);
  FetchObsResponse(FetchObsResponse&& from) noexcept
    : FetchObsResponse() {
    *this = ::std::move(from);
  }

  inline FetchObsResponse& operator=(const FetchObsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline FetchObsResponse& operator=(FetchObsResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FetchObsResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FetchObsResponse* internal_default_instance() {
    return reinterpret_cast<const FetchObsResponse*>(
               &_FetchObsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FetchObsResponse& a, FetchObsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(FetchObsResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FetchObsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FetchObsResponse* New() const final {
    return CreateMaybeMessage<FetchObsResponse>(nullptr);
  }

  FetchObsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FetchObsResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FetchObsResponse& from);
  void MergeFrom(const FetchObsResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FetchObsResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mujoco.FetchObsResponse";
  }
  protected:
  explicit FetchObsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mujoco_5fservice_2eproto);
    return ::descriptor_table_mujoco_5fservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBaseAngVelFieldNumber = 1,
    kJointPosFieldNumber = 2,
    kJointVelFieldNumber = 3,
  };
  // repeated float base_ang_vel = 1;
  int base_ang_vel_size() const;
  private:
  int _internal_base_ang_vel_size() const;
  public:
  void clear_base_ang_vel();
  private:
  float _internal_base_ang_vel(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_base_ang_vel() const;
  void _internal_add_base_ang_vel(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_base_ang_vel();
  public:
  float base_ang_vel(int index) const;
  void set_base_ang_vel(int index, float value);
  void add_base_ang_vel(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      base_ang_vel() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_base_ang_vel();

  // repeated float joint_pos = 2;
  int joint_pos_size() const;
  private:
  int _internal_joint_pos_size() const;
  public:
  void clear_joint_pos();
  private:
  float _internal_joint_pos(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_joint_pos() const;
  void _internal_add_joint_pos(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_joint_pos();
  public:
  float joint_pos(int index) const;
  void set_joint_pos(int index, float value);
  void add_joint_pos(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      joint_pos() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_joint_pos();

  // repeated float joint_vel = 3;
  int joint_vel_size() const;
  private:
  int _internal_joint_vel_size() const;
  public:
  void clear_joint_vel();
  private:
  float _internal_joint_vel(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_joint_vel() const;
  void _internal_add_joint_vel(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_joint_vel();
  public:
  float joint_vel(int index) const;
  void set_joint_vel(int index, float value);
  void add_joint_vel(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      joint_vel() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_joint_vel();

  // @@protoc_insertion_point(class_scope:mujoco.FetchObsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > base_ang_vel_;
  mutable std::atomic<int> _base_ang_vel_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > joint_pos_;
  mutable std::atomic<int> _joint_pos_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > joint_vel_;
  mutable std::atomic<int> _joint_vel_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mujoco_5fservice_2eproto;
};
// -------------------------------------------------------------------

class WriteTorqueRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mujoco.WriteTorqueRequest) */ {
 public:
  inline WriteTorqueRequest() : WriteTorqueRequest(nullptr) {};
  virtual ~WriteTorqueRequest();

  WriteTorqueRequest(const WriteTorqueRequest& from);
  WriteTorqueRequest(WriteTorqueRequest&& from) noexcept
    : WriteTorqueRequest() {
    *this = ::std::move(from);
  }

  inline WriteTorqueRequest& operator=(const WriteTorqueRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline WriteTorqueRequest& operator=(WriteTorqueRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WriteTorqueRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WriteTorqueRequest* internal_default_instance() {
    return reinterpret_cast<const WriteTorqueRequest*>(
               &_WriteTorqueRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(WriteTorqueRequest& a, WriteTorqueRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(WriteTorqueRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WriteTorqueRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WriteTorqueRequest* New() const final {
    return CreateMaybeMessage<WriteTorqueRequest>(nullptr);
  }

  WriteTorqueRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WriteTorqueRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WriteTorqueRequest& from);
  void MergeFrom(const WriteTorqueRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WriteTorqueRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mujoco.WriteTorqueRequest";
  }
  protected:
  explicit WriteTorqueRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mujoco_5fservice_2eproto);
    return ::descriptor_table_mujoco_5fservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTorquesFieldNumber = 1,
  };
  // repeated float torques = 1;
  int torques_size() const;
  private:
  int _internal_torques_size() const;
  public:
  void clear_torques();
  private:
  float _internal_torques(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_torques() const;
  void _internal_add_torques(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_torques();
  public:
  float torques(int index) const;
  void set_torques(int index, float value);
  void add_torques(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      torques() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_torques();

  // @@protoc_insertion_point(class_scope:mujoco.WriteTorqueRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > torques_;
  mutable std::atomic<int> _torques_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mujoco_5fservice_2eproto;
};
// -------------------------------------------------------------------

class WriteTorqueResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mujoco.WriteTorqueResponse) */ {
 public:
  inline WriteTorqueResponse() : WriteTorqueResponse(nullptr) {};
  virtual ~WriteTorqueResponse();

  WriteTorqueResponse(const WriteTorqueResponse& from);
  WriteTorqueResponse(WriteTorqueResponse&& from) noexcept
    : WriteTorqueResponse() {
    *this = ::std::move(from);
  }

  inline WriteTorqueResponse& operator=(const WriteTorqueResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline WriteTorqueResponse& operator=(WriteTorqueResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WriteTorqueResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WriteTorqueResponse* internal_default_instance() {
    return reinterpret_cast<const WriteTorqueResponse*>(
               &_WriteTorqueResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(WriteTorqueResponse& a, WriteTorqueResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(WriteTorqueResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WriteTorqueResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WriteTorqueResponse* New() const final {
    return CreateMaybeMessage<WriteTorqueResponse>(nullptr);
  }

  WriteTorqueResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WriteTorqueResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WriteTorqueResponse& from);
  void MergeFrom(const WriteTorqueResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WriteTorqueResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mujoco.WriteTorqueResponse";
  }
  protected:
  explicit WriteTorqueResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mujoco_5fservice_2eproto);
    return ::descriptor_table_mujoco_5fservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:mujoco.WriteTorqueResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mujoco_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FetchObsRequest

// -------------------------------------------------------------------

// FetchObsResponse

// repeated float base_ang_vel = 1;
inline int FetchObsResponse::_internal_base_ang_vel_size() const {
  return base_ang_vel_.size();
}
inline int FetchObsResponse::base_ang_vel_size() const {
  return _internal_base_ang_vel_size();
}
inline void FetchObsResponse::clear_base_ang_vel() {
  base_ang_vel_.Clear();
}
inline float FetchObsResponse::_internal_base_ang_vel(int index) const {
  return base_ang_vel_.Get(index);
}
inline float FetchObsResponse::base_ang_vel(int index) const {
  // @@protoc_insertion_point(field_get:mujoco.FetchObsResponse.base_ang_vel)
  return _internal_base_ang_vel(index);
}
inline void FetchObsResponse::set_base_ang_vel(int index, float value) {
  base_ang_vel_.Set(index, value);
  // @@protoc_insertion_point(field_set:mujoco.FetchObsResponse.base_ang_vel)
}
inline void FetchObsResponse::_internal_add_base_ang_vel(float value) {
  base_ang_vel_.Add(value);
}
inline void FetchObsResponse::add_base_ang_vel(float value) {
  _internal_add_base_ang_vel(value);
  // @@protoc_insertion_point(field_add:mujoco.FetchObsResponse.base_ang_vel)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
FetchObsResponse::_internal_base_ang_vel() const {
  return base_ang_vel_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
FetchObsResponse::base_ang_vel() const {
  // @@protoc_insertion_point(field_list:mujoco.FetchObsResponse.base_ang_vel)
  return _internal_base_ang_vel();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
FetchObsResponse::_internal_mutable_base_ang_vel() {
  return &base_ang_vel_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
FetchObsResponse::mutable_base_ang_vel() {
  // @@protoc_insertion_point(field_mutable_list:mujoco.FetchObsResponse.base_ang_vel)
  return _internal_mutable_base_ang_vel();
}

// repeated float joint_pos = 2;
inline int FetchObsResponse::_internal_joint_pos_size() const {
  return joint_pos_.size();
}
inline int FetchObsResponse::joint_pos_size() const {
  return _internal_joint_pos_size();
}
inline void FetchObsResponse::clear_joint_pos() {
  joint_pos_.Clear();
}
inline float FetchObsResponse::_internal_joint_pos(int index) const {
  return joint_pos_.Get(index);
}
inline float FetchObsResponse::joint_pos(int index) const {
  // @@protoc_insertion_point(field_get:mujoco.FetchObsResponse.joint_pos)
  return _internal_joint_pos(index);
}
inline void FetchObsResponse::set_joint_pos(int index, float value) {
  joint_pos_.Set(index, value);
  // @@protoc_insertion_point(field_set:mujoco.FetchObsResponse.joint_pos)
}
inline void FetchObsResponse::_internal_add_joint_pos(float value) {
  joint_pos_.Add(value);
}
inline void FetchObsResponse::add_joint_pos(float value) {
  _internal_add_joint_pos(value);
  // @@protoc_insertion_point(field_add:mujoco.FetchObsResponse.joint_pos)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
FetchObsResponse::_internal_joint_pos() const {
  return joint_pos_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
FetchObsResponse::joint_pos() const {
  // @@protoc_insertion_point(field_list:mujoco.FetchObsResponse.joint_pos)
  return _internal_joint_pos();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
FetchObsResponse::_internal_mutable_joint_pos() {
  return &joint_pos_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
FetchObsResponse::mutable_joint_pos() {
  // @@protoc_insertion_point(field_mutable_list:mujoco.FetchObsResponse.joint_pos)
  return _internal_mutable_joint_pos();
}

// repeated float joint_vel = 3;
inline int FetchObsResponse::_internal_joint_vel_size() const {
  return joint_vel_.size();
}
inline int FetchObsResponse::joint_vel_size() const {
  return _internal_joint_vel_size();
}
inline void FetchObsResponse::clear_joint_vel() {
  joint_vel_.Clear();
}
inline float FetchObsResponse::_internal_joint_vel(int index) const {
  return joint_vel_.Get(index);
}
inline float FetchObsResponse::joint_vel(int index) const {
  // @@protoc_insertion_point(field_get:mujoco.FetchObsResponse.joint_vel)
  return _internal_joint_vel(index);
}
inline void FetchObsResponse::set_joint_vel(int index, float value) {
  joint_vel_.Set(index, value);
  // @@protoc_insertion_point(field_set:mujoco.FetchObsResponse.joint_vel)
}
inline void FetchObsResponse::_internal_add_joint_vel(float value) {
  joint_vel_.Add(value);
}
inline void FetchObsResponse::add_joint_vel(float value) {
  _internal_add_joint_vel(value);
  // @@protoc_insertion_point(field_add:mujoco.FetchObsResponse.joint_vel)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
FetchObsResponse::_internal_joint_vel() const {
  return joint_vel_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
FetchObsResponse::joint_vel() const {
  // @@protoc_insertion_point(field_list:mujoco.FetchObsResponse.joint_vel)
  return _internal_joint_vel();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
FetchObsResponse::_internal_mutable_joint_vel() {
  return &joint_vel_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
FetchObsResponse::mutable_joint_vel() {
  // @@protoc_insertion_point(field_mutable_list:mujoco.FetchObsResponse.joint_vel)
  return _internal_mutable_joint_vel();
}

// -------------------------------------------------------------------

// WriteTorqueRequest

// repeated float torques = 1;
inline int WriteTorqueRequest::_internal_torques_size() const {
  return torques_.size();
}
inline int WriteTorqueRequest::torques_size() const {
  return _internal_torques_size();
}
inline void WriteTorqueRequest::clear_torques() {
  torques_.Clear();
}
inline float WriteTorqueRequest::_internal_torques(int index) const {
  return torques_.Get(index);
}
inline float WriteTorqueRequest::torques(int index) const {
  // @@protoc_insertion_point(field_get:mujoco.WriteTorqueRequest.torques)
  return _internal_torques(index);
}
inline void WriteTorqueRequest::set_torques(int index, float value) {
  torques_.Set(index, value);
  // @@protoc_insertion_point(field_set:mujoco.WriteTorqueRequest.torques)
}
inline void WriteTorqueRequest::_internal_add_torques(float value) {
  torques_.Add(value);
}
inline void WriteTorqueRequest::add_torques(float value) {
  _internal_add_torques(value);
  // @@protoc_insertion_point(field_add:mujoco.WriteTorqueRequest.torques)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
WriteTorqueRequest::_internal_torques() const {
  return torques_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
WriteTorqueRequest::torques() const {
  // @@protoc_insertion_point(field_list:mujoco.WriteTorqueRequest.torques)
  return _internal_torques();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
WriteTorqueRequest::_internal_mutable_torques() {
  return &torques_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
WriteTorqueRequest::mutable_torques() {
  // @@protoc_insertion_point(field_mutable_list:mujoco.WriteTorqueRequest.torques)
  return _internal_mutable_torques();
}

// -------------------------------------------------------------------

// WriteTorqueResponse

// bool success = 1;
inline void WriteTorqueResponse::clear_success() {
  success_ = false;
}
inline bool WriteTorqueResponse::_internal_success() const {
  return success_;
}
inline bool WriteTorqueResponse::success() const {
  // @@protoc_insertion_point(field_get:mujoco.WriteTorqueResponse.success)
  return _internal_success();
}
inline void WriteTorqueResponse::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void WriteTorqueResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:mujoco.WriteTorqueResponse.success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mujoco

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mujoco_5fservice_2eproto
