// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mujoco_service.proto

#include "mujoco_service.pb.h"
#include "mujoco_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace mujoco {

static const char* MuJoCoService_method_names[] = {
  "/mujoco.MuJoCoService/FetchObs",
  "/mujoco.MuJoCoService/WriteTorque",
};

std::unique_ptr< MuJoCoService::Stub> MuJoCoService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MuJoCoService::Stub> stub(new MuJoCoService::Stub(channel));
  return stub;
}

MuJoCoService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_FetchObs_(MuJoCoService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WriteTorque_(MuJoCoService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MuJoCoService::Stub::FetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::mujoco::FetchObsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_FetchObs_, context, request, response);
}

void MuJoCoService::Stub::experimental_async::FetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest* request, ::mujoco::FetchObsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_FetchObs_, context, request, response, std::move(f));
}

void MuJoCoService::Stub::experimental_async::FetchObs(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::FetchObsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_FetchObs_, context, request, response, std::move(f));
}

void MuJoCoService::Stub::experimental_async::FetchObs(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest* request, ::mujoco::FetchObsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_FetchObs_, context, request, response, reactor);
}

void MuJoCoService::Stub::experimental_async::FetchObs(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::FetchObsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_FetchObs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mujoco::FetchObsResponse>* MuJoCoService::Stub::AsyncFetchObsRaw(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mujoco::FetchObsResponse>::Create(channel_.get(), cq, rpcmethod_FetchObs_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mujoco::FetchObsResponse>* MuJoCoService::Stub::PrepareAsyncFetchObsRaw(::grpc::ClientContext* context, const ::mujoco::FetchObsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mujoco::FetchObsResponse>::Create(channel_.get(), cq, rpcmethod_FetchObs_, context, request, false);
}

::grpc::Status MuJoCoService::Stub::WriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::mujoco::WriteTorqueResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_WriteTorque_, context, request, response);
}

void MuJoCoService::Stub::experimental_async::WriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest* request, ::mujoco::WriteTorqueResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_WriteTorque_, context, request, response, std::move(f));
}

void MuJoCoService::Stub::experimental_async::WriteTorque(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::WriteTorqueResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_WriteTorque_, context, request, response, std::move(f));
}

void MuJoCoService::Stub::experimental_async::WriteTorque(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest* request, ::mujoco::WriteTorqueResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_WriteTorque_, context, request, response, reactor);
}

void MuJoCoService::Stub::experimental_async::WriteTorque(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mujoco::WriteTorqueResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_WriteTorque_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mujoco::WriteTorqueResponse>* MuJoCoService::Stub::AsyncWriteTorqueRaw(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mujoco::WriteTorqueResponse>::Create(channel_.get(), cq, rpcmethod_WriteTorque_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mujoco::WriteTorqueResponse>* MuJoCoService::Stub::PrepareAsyncWriteTorqueRaw(::grpc::ClientContext* context, const ::mujoco::WriteTorqueRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mujoco::WriteTorqueResponse>::Create(channel_.get(), cq, rpcmethod_WriteTorque_, context, request, false);
}

MuJoCoService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MuJoCoService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MuJoCoService::Service, ::mujoco::FetchObsRequest, ::mujoco::FetchObsResponse>(
          [](MuJoCoService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::mujoco::FetchObsRequest* req,
             ::mujoco::FetchObsResponse* resp) {
               return service->FetchObs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MuJoCoService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MuJoCoService::Service, ::mujoco::WriteTorqueRequest, ::mujoco::WriteTorqueResponse>(
          [](MuJoCoService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::mujoco::WriteTorqueRequest* req,
             ::mujoco::WriteTorqueResponse* resp) {
               return service->WriteTorque(ctx, req, resp);
             }, this)));
}

MuJoCoService::Service::~Service() {
}

::grpc::Status MuJoCoService::Service::FetchObs(::grpc::ServerContext* context, const ::mujoco::FetchObsRequest* request, ::mujoco::FetchObsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MuJoCoService::Service::WriteTorque(::grpc::ServerContext* context, const ::mujoco::WriteTorqueRequest* request, ::mujoco::WriteTorqueResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mujoco

